config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/index'
  root 'home#index'
  
  resources :categories, only: [:show, :index]  do 
    resources :sub_categories, only: [:show]  do 
      resources :items, only: [:show] 
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :sub_categories, dependent: :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :sub_category, dependent: :destroy
  
  mount_uploader :image, ImageUploader

  validates :name,:price, presence: true

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :items, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  	def load_categories
  		@categories = Category.all
  	end
  
	  def set_category(category_id)
	    @category = Category.find category_id
	  end

	  def set_sub_category(sub_category_id)
	    @sub_category = @category.sub_categories.find sub_category_id
	  end

	  def set_item(item_id)
	  	@item = @sub_category.items.find item_id
	  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :initialize_category

	def show
		@sub_categories = @category.sub_categories
	end

	def index
		load_categories
	end

	private
  
	  def initialize_category 
	    set_category(params[:id])
	  end
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :initialize_category
  before_action :initialize_sub_category
  before_action :initialize_item
	
	def show
	end

	private

		def initialize_category
			set_category(params[:category_id])
		end

		def initialize_sub_category
			set_sub_category(params[:sub_category_id])
		end

		def initialize_item
			set_item(params[:id])
		end

end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
	before_action :initialize_category
  before_action :initialize_sub_category
	
	def show
		@items = @sub_category.items
	end

	private 

		def initialize_category
			set_category(params[:category_id])
		end

		def initialize_sub_category
			set_sub_category(params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/categories/_sub_category.html.erb
<%= image_tag(sub_category.image_url(:thumb)) %>
<%= link_to 'View Products',category_sub_category_path(@category,sub_category) %>

app/views/categories/show.html.erb
<% if @sub_categories.present? %>
  <%= render partial: "sub_category", collection: @sub_categories %>
<% else %>  
  <p>No sub categories</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/show.html.erb
<li><%= link_to @sub_category.name.to_s,category_sub_category_path(@category, @sub_category)%></li>
<li><%= @item.name %></li>
<li><%= @item.detail %></li>
<%= image_tag @item.image_url(:thumb) %>
 <b><%=@category.name %></b>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ShoppingCart" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ShoppingCart</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", categories_path  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ShoppingCart" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ShoppingCart</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/sub_categories/_item.html.erb
<div class="col-md-12">
  <div class="col-md-1">
    <div class="product-img product-img-brd">
        <a href = "#"><%= image_tag(item.image_url, class: "full-width img-responsive", style: "width:40px;") %></a>
    </div>
  </div>
  <div class="col-md-7"> 
    <div class="product-description product-description-brd margin-bottom-30">
      <div class="pull-left" style="overflow:hidden;">
        <h4 class="title-price"><%= link_to item.name,category_sub_category_item_path(@category,@sub_category,item) %></h4>
      </div>
    </div> 
  </div>
  <div class="col-md-2"> 
    <div class="product-description product-description-brd margin-bottom-30">
        <div class="pull-left" style="overflow:hidden;">
          <h4 class="title-price">£ <%= item.price %></h4>
        </div>
     </div> 
  </div>
</div>

app/views/sub_categories/show.html.erb
<% if @items.present? %>
	<%= render partial: "item", collection: @items %>
<% else %>  
	<p>No Items</p>
<% end %>